name: Unzip and setup repo
on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Unzip and restructure
        run: |
          unzip bassito-remote.zip
          cp -r bassito-remote/* .
          cp bassito-remote/.env.example .
          cp bassito-remote/.gitignore .
          rm -rf bassito-remote/ bassito-remote.zip
          rm -rf .github/workflows/unzip.yml
          
      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Unzip: project structure ready"
          git push
